name: Access private repositories
runs:
  using: composite
  steps:
    - name: Inject access token
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        git config --global url.https://$ACCESS_TOKEN@github.com/.insteadOf git@github.com:
