name: Access private repositories
inputs:
  access-token:
    description: "The GitHub access token"
    required: true
runs:
  using: composite
  steps:
    - name: Inject HTTPS token
      shell: bash
      run: |
        git config --global url."https://${{ inputs.access-token }}@github.com/".insteadOf "git@github.com:"
